/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_ReadFileThread */

#ifndef _Included_util_ReadFileThread
#define _Included_util_ReadFileThread
#ifdef __cplusplus
extern "C" {
#endif
#undef util_ReadFileThread_MIN_PRIORITY
#define util_ReadFileThread_MIN_PRIORITY 1L
#undef util_ReadFileThread_NORM_PRIORITY
#define util_ReadFileThread_NORM_PRIORITY 5L
#undef util_ReadFileThread_MAX_PRIORITY
#define util_ReadFileThread_MAX_PRIORITY 10L
/*
 * Class:     util_ReadFileThread
 * Method:    getStringFromNative
 * Signature: ([S[D)V
 */
JNIEXPORT void JNICALL Java_util_ReadFileThread_getStringFromNative
  (JNIEnv *, jobject, jshortArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
